title: Site

tabs:
  content:
    label: Content
    sections:
      pages:
        type: pages
  css:
    label: CSS
    sections:
      fields:
        type: fields
        fields:
          css:
            type: csslint
            label: Custom CSS
            buttons: false
            spellcheck: false
            translate: false
  translations:
    label: Translations
    sections:
      fieldstranslations:
        type: fields
        fields:
          translations:
            translate: false
            type: structure
            fields:
              english:
                type: text
                label: English
              german:
                type: text
                label: German